services:
 db:
   image: postgres:16-alpine
   environment:
     POSTGRES_DB: ${DB_NAME}
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env

 django-web:
   build: .
   container_name: django-docker
   expose:
     - 8000
   depends_on:
     - db
   environment:
     SECRET_KEY: ${SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
     ALLOWED_HOSTS: ${ALLOWED_HOSTS}
     DB_ENGINE: ${DB_ENGINE}
     DB_NAME: ${DB_NAME}
     DB_USER: ${DB_USER}
     DB_PASSWORD: ${DB_PASSWORD}
     DB_HOST: ${DB_HOST}
     DB_PORT: ${DB_PORT}
   env_file:
     - .env
 nginx:
   build: ./nginx
   volumes:
    - static_volume:/home/app/web/static
    - media_volume:/home/app/web/media
   ports:
    - 1337:80
   depends_on:
    - django-web
volumes:
   postgres_data:
   static_volume:
   media_volume: